import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Surfaces — wheat hierarchy
        surface: '#F5DEB3',
        'surface-dim': '#D0C5AA',
        'surface-bright': '#FBF2E0',
        'surface-container-lowest': '#E8D8B4',
        'surface-container-low': '#EDDFC0',
        'surface-container': '#FBF2E0',
        'surface-container-high': '#F0E6CC',
        'surface-container-highest': '#EDDFC0',
        'on-surface': '#2C2C2C',
        'on-surface-variant': '#5C5850',
        'inverse-surface': '#2C2C2C',
        'inverse-on-surface': '#FBF2E0',
        outline: '#8C8878',
        'outline-variant': '#E0D5BA',
        'surface-tint': '#C5D8C0',
        // Brand
        'brand-warm': '#F0E6CC',
        'brand-card': '#FBF2E0',
        'brand-border': '#E0D5BA',
        // Primary — mint green (same lightness as wheat)
        primary: '#C5D8C0',
        'on-primary': '#2C2C2C',
        'primary-container': '#D8E8D0',
        'on-primary-container': '#2A3A24',
        'inverse-primary': '#9CAF92',
        'primary-fixed': '#D8E8D0',
        'primary-fixed-dim': '#C8DCC0',
        'on-primary-fixed': '#1A2A14',
        'on-primary-fixed-variant': '#4A5A44',
        // Secondary — sage green
        secondary: '#9CAF92',
        'on-secondary': '#1A2418',
        'secondary-container': '#E5EDE2',
        'on-secondary-container': '#2A3A28',
        'secondary-fixed': '#E5EDE2',
        'secondary-fixed-dim': '#D0DCC8',
        'on-secondary-fixed': '#0A1408',
        'on-secondary-fixed-variant': '#3A5A38',
        // Tertiary / Gold
        tertiary: '#D4B872',
        'on-tertiary': '#3A3020',
        'tertiary-container': '#F8F2E0',
        'on-tertiary-container': '#5A4620',
        'tertiary-fixed': '#F8F2E0',
        'tertiary-fixed-dim': '#E8D8B0',
        'on-tertiary-fixed': '#1A1408',
        'on-tertiary-fixed-variant': '#7A6A30',
        // Status palette
        sage: '#9CAF92',
        gold: '#D4B872',
        clay: '#D4937A',
        'dusty-blue': '#7A8FA6',
        'soft-olive': '#A4B89A',
        // Error — warm rose
        error: '#D4786E',
        'on-error': '#FFFFFF',
        'error-container': '#F5E8E5',
        'on-error-container': '#4A2018',
        background: '#F5DEB3',
        'on-background': '#2C2C2C',
        'surface-variant': '#EDDFC0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '0.5rem',
        xl: '1.5rem',
        '2xl': '12px',
        full: '9999px',
      },
      spacing: {
        xxl: '48px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        gutter: '16px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
      },
      fontFamily: {
        h1: ['var(--font-changa-one)', 'Changa One', 'serif'],
        'h1-mobile': ['var(--font-changa-one)', 'Changa One', 'serif'],
        h2: ['var(--font-changa-one)', 'Changa One', 'serif'],
        'body-lg': ['var(--font-lexend)', 'Lexend', 'sans-serif'],
        'body-md': ['var(--font-lexend)', 'Lexend', 'sans-serif'],
        logo: ['var(--font-anton)', 'Anton', 'sans-serif'],
        'label-md': ['var(--font-nanum)', 'Nanum Gothic', 'sans-serif'],
        'label-sm': ['var(--font-nanum)', 'Nanum Gothic', 'sans-serif'],
        button: ['var(--font-lexend)', 'Lexend', 'sans-serif'],
        metric: ['var(--font-nanum)', 'Nanum Gothic', 'sans-serif'],
      },
      fontSize: {
        h1: ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'h1-mobile': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        h2: ['24px', { lineHeight: '32px', fontWeight: '400' }],
        logo: ['24px', { lineHeight: '32px', letterSpacing: '0.15em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        button: ['16px', { lineHeight: '20px', fontWeight: '500' }],
        metric: ['20px', { lineHeight: '24px', fontWeight: '700' }],
      },
      boxShadow: {
        paper: '0px 4px 12px rgba(44, 44, 44, 0.06)',
      },
    },
  },
  plugins: [],
};

export default config;
